# Generated by Django 6.0.5 on 2026-05-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="ctc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="notice_period",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="personal_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="personal_mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="reporting_manager",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
