# Generated by Django 6.0.5 on 2026-05-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=100)),
                ("material_code", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=20)),
            ],
        ),
    ]
