# Generated by Django 6.0.5 on 2026-05-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_stocktransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="size",
            field=models.CharField(default="NA", max_length=50),
            preserve_default=False,
        ),
    ]
