# Generated by Django 6.0.5 on 2026-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_material_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStockSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Stock Summary",
                "verbose_name_plural": "Project Stock Summary",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.CharField(
                choices=[
                    ("Pipe", "Pipe"),
                    ("Valve", "Valve"),
                    ("Fitting", "Fitting"),
                    ("Instrument", "Instrument"),
                    ("Electrical", "Electrical"),
                    ("Consumable", "Consumable"),
                ],
                default="Pipe",
                max_length=50,
            ),
        ),
    ]
