# Generated by Django 6.0.5 on 2026-05-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_projectstocksummary_material_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="min_stock",
            field=models.FloatField(default=0),
        ),
    ]
