# Generated by Django 6.0.5 on 2026-05-27 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_material_min_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                ("transfer_date", models.DateTimeField(auto_now_add=True)),
                (
                    "from_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_project",
                        to="inventory.project",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.material",
                    ),
                ),
                (
                    "to_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_project",
                        to="inventory.project",
                    ),
                ),
            ],
        ),
    ]
