# Generated by Django 6.0.5 on 2026-05-27 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_materialtransfer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectStockSummary",
        ),
        migrations.AddField(
            model_name="material",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="material",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="materialtransfer",
            name="approved_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="materialtransfer",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialtransfer",
            name="transfer_no",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="approved_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="transaction_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="transaction_no",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="material",
            name="material_code",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="material",
            name="material_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="material",
            name="size",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_code",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(max_length=255),
        ),
    ]
