# Generated by Django 6.0.5 on 2026-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_delete_projectstocksummary_material_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="approved_qty",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="grn_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="hold_qty",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="qc_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="qc_done_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="qc_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Partial", "Partial"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="received_qty",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="rejected_qty",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="vendor_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("GRN", "GRN"), ("IN", "IN"), ("OUT", "OUT")], max_length=20
            ),
        ),
    ]
